spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
server:
  context-path: /oa
